package sshkeys

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	ManagedBy       = "# Managed by sshutil. Managed blocks are regenerated; do not edit."
	IncludeLine     = "Include ~/.ssh/config.d/*"
	ConfigDDirName  = "config.d"
	TailnetFileName = "90-tailnet"
)

var ClientDefaults = ManagedBy + `
Host *
    AddKeysToAgent yes
    IdentitiesOnly yes
    HashKnownHosts yes
    ServerAliveInterval 60
    ServerAliveCountMax 3
`

var GitHubBlock = ManagedBy + `
Host github.com
    IdentityFile ~/.ssh/id_github
    IdentitiesOnly yes
    User git
`

var PersonalBlock = ManagedBy + `
Host *
    IdentityFile ~/.ssh/id_personal
`

func ServiceBlock(service string) string {
	return fmt.Sprintf("%s\nHost %s\n    IdentityFile ~/.ssh/id_%s\n    IdentitiesOnly yes\n", ManagedBy, service, service)
}

func TailnetPeerBlock(alias, hostname, user string) string {
	return fmt.Sprintf("%s\nHost %s\n    HostName %s\n    User %s\n    IdentityFile ~/.ssh/id_personal\n    IdentitiesOnly yes\n", ManagedBy, alias, hostname, user)
}

func WriteConfigFiles(sshDir string, services []string) error {
	d := filepath.Join(sshDir, ConfigDDirName)
	if err := os.MkdirAll(d, 0o700); err != nil {
		return err
	}
	_ = os.Chmod(d, 0o700)
	_ = os.Chmod(sshDir, 0o700)
	files := map[string]string{
		"00-defaults": ClientDefaults,
		"10-github":   GitHubBlock,
		"10-personal": PersonalBlock,
	}
	for _, s := range services {
		files["20-"+s] = ServiceBlock(s)
	}
	for name, content := range files {
		if err := os.WriteFile(filepath.Join(d, name), []byte(content), 0o644); err != nil {
			return err
		}
	}
	return EnsureMainConfig(sshDir)
}

func WriteServiceConfig(sshDir, service string) error {
	d := filepath.Join(sshDir, ConfigDDirName)
	if err := os.MkdirAll(d, 0o700); err != nil {
		return err
	}
	_ = os.Chmod(d, 0o700)
	return os.WriteFile(filepath.Join(d, "20-"+service), []byte(ServiceBlock(service)), 0o644)
}

func WriteTailnetConfig(sshDir string, blocks []string) error {
	d := filepath.Join(sshDir, ConfigDDirName)
	if err := os.MkdirAll(d, 0o700); err != nil {
		return err
	}
	_ = os.Chmod(d, 0o700)
	content := ManagedBy + "\n# Generated by 'sshutil sync'. Do not edit.\n" + strings.Join(blocks, "\n")
	return os.WriteFile(filepath.Join(d, TailnetFileName), []byte(content), 0o644)
}

func EnsureMainConfig(sshDir string) error {
	main := filepath.Join(sshDir, "config")
	want := ManagedBy + "\n" + IncludeLine + "\n"
	data, err := os.ReadFile(main)
	if err == nil {
		if strings.Contains(string(data), ManagedBy) {
			return os.WriteFile(main, []byte(want), 0o644)
		}
		backup := filepath.Join(sshDir, "config.pre-sshutil")
		if _, err := os.Stat(backup); err == nil {
			return fmt.Errorf("backup %s already exists; resolve and retry", backup)
		}
		if err := os.Rename(main, backup); err != nil {
			return err
		}
	} else if !os.IsNotExist(err) {
		return err
	}
	return os.WriteFile(main, []byte(want), 0o644)
}

const BashrcSnippet = `# >>> sshutil >>>
if command -v keychain >/dev/null 2>&1; then
    eval "$(keychain --eval --quiet id_personal id_github)"
fi
# <<< sshutil <<<
`

func EnsureBashrc() (bool, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return false, err
	}
	p := filepath.Join(home, ".bashrc")
	data, err := os.ReadFile(p)
	if err == nil && strings.Contains(string(data), "# >>> sshutil >>>") {
		return false, nil
	}
	f, err := os.OpenFile(p, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
	if err != nil {
		return false, err
	}
	defer f.Close()
	if len(data) > 0 && !strings.HasSuffix(string(data), "\n") {
		if _, err := f.WriteString("\n"); err != nil {
			return false, err
		}
	}
	if _, err := f.WriteString(BashrcSnippet); err != nil {
		return false, err
	}
	return true, nil
}
